package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mcp_lib",
    srcs = glob([
        "mcp/**/*.cc",
    ]),
    hdrs = glob([
        "mcp/**/*.h",
    ]),
    deps = [
    ],
)