package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mcp_lib",
    srcs = glob([
        "client/**/*.cc",
        "common/**/*.cc",
        "io/**/*.cc",
        "server/**/*.cc",
    ]),
    hdrs = glob([
        "client/**/*.h",
        "common/**/*.h",
        "io/**/*.h",
        "server/**/*.h",
    ]),
    deps = [
    ],
    alwayslink = True,
)